"
I provide support for programmatic CSS generation using Smalltalk.
Extend the LWStyledPage in your main page (or otherwise install the LWStyleAttributeRenderer).

Style attributes can then be specified as 1 argument blocks where.

Also provides support for CSS calculations. The CSS values and variables support
the +,-,* and / binary messages. 
"
Class {
	#name : #ManifestLiveWebStyling,
	#superclass : #PackageManifest,
	#category : #'LiveWeb-Styling-Manifest'
}
