Class {
	#name : #LWDevStyles,
	#superclass : #Object,
	#category : #'LiveWeb-Developer'
}

{ #category : #'as yet unclassified' }
LWDevStyles >> formField [ 
 ^ #class -> ''
]

{ #category : #'as yet unclassified' }
LWDevStyles >> formFieldLabel [ 
 ^ #class -> ''
]

{ #category : #'as yet unclassified' }
LWDevStyles >> formInput: required [
 ^ #class -> ''
	
]

{ #category : #'as yet unclassified' }
LWDevStyles >> formInputAndError [ 
 ^ #class -> ''
	
]
